### ISSUE TITLE
Is there any hope to get the project back in action ?

### ISSUE THREAD

**Issue by bogas04** [zpao/spidernode#10]
Hello from future! MSFT is working towards bringing Chakra and Node together, while V8 is still growing strong with projects like Electron. Recently Brave browser was released which is essentially built on top of Electron. 

As always, Mozilla has vouched for competition and SpiderMonkey is an excellent project in itself. I can't see why SpiderNode shouldn't be resurrected now when shift from browser choice is coming to engine choice for developers. 

So, any hope for getting it back ?

**Comment by zpao** [comment]
Not at this time, unless there is some effort within Mozilla that I haven't heard of. [JXCore](http://jxcore.com/home/) is probably your best bet at this point - perhaps they will lead the effort.

**Comment by mautematico** [comment]
I'll leave a coment right here just to get updates on the conversation, if there are any. :)

**Comment by zpao** [comment]
FYI: In the future you can subscribe without sending an email to all watchers (not a big deal here but in other projects it's annoying because you could be sending a useless comment to thousands of people). There's a nice "subscribe" button in the right hand column.

![image](https://cloud.githubusercontent.com/assets/8445/12856623/aaf7f780-cbfa-11e5-9c90-3d274ee8cedd.png)
